def Contenido():
    matriz = {"Origen": [["Parque Nacional Volcan Arenal", "/Arenal/"],
                        ["Dominical", "/Dominical/"],
                        ["Monteverde", "/Monteverde/"],
                        ["Parque Nacional Tortuguero", "/Tortuguero/"],
                        ["Puerto Jimenez", "/PJimenez/"],
                        ["Parque Nacional Rincon de La Vieja", "/RinconDeLaVieja/"],
                        ["Volcan Barva", "/VolcanBarva/"],
                        ["Bijagua", "/Bijagua/"],
                        ["Puerto Viejo de Heredia", "/PuertoViejoH/"],
                        ["Parque Nacional Palo Verde", "/PaloVerde/"],
                        ["Parque Nacional Barbilla", "/Barbilla/"],
                        ["Parque Nacional Los Quetzales", "/Quetzales/"],
                        ["Uvita", "/Uvita/"],
                        ["Parque Nacional Tapanti", "/Tapanti/"],
                        ["Parque Nacional Volcan Tenorio", "/VolcanTenorio/"],
                        ["Puerto Viejo de Talamanca", "/PuertoViejoT/"],
                        ["Parque Nacional Chirripo", "/Chirripo/"],
                        ["Parque Nacional Santa Rosa", "/SantaRosa/"],
                        ["Parque Nacional La Amistad", "/LaAmistad/"],
                        ["Refugio Nacional Gandoca Manzanillo", "/Gandoca/"],
                        ["Refugio Cano Negro", "/CanoNegro/"],
                        ["Parque Nacional Braulio Carrillo", "/BraulioCarrillo/"],
                        ["Parque Nacional Barra Honda", "/BarraHonda/"]],

                "Destino": [["Parque Nacional Volcan Arenal", "/DestinoArenal/"],
                        ["Dominical", "/DestinoDominical/"],
                        ["Monteverde", "/DestinoMonteverde/"],
                        ["Parque Nacional Tortuguero", "/DestinoTortuguero/"],
                        ["Puerto Jimenez", "/DestinoPJimenez/"],
                        ["Parque Nacional Rincon de La Vieja", "/DestinoRinconDeLaVieja/"],
                        ["Volcan Barva", "/DestinoVolcanBarva/"],
                        ["Bijagua", "/DestinoBijagua/"],
                        ["Puerto Viejo de Heredia", "/DestinoPuertoViejoH/"],
                        ["Parque Nacional Palo Verde", "/DestinoPaloVerde/"],
                        ["Parque Nacional Barbilla", "/DestinoBarbilla/"],
                        ["Parque Nacional Los Quetzales", "/DestinoQuetzales/"],
                        ["Uvita", "/DestinoUvita/"],
                        ["Parque Nacional Tapanti", "/DestinoTapanti/"],
                        ["Parque Nacional Volcan Tenorio", "/DestinoVolcanTenorio/"],
                        ["Puerto Viejo de Talamanca", "/DestinoPuertoViejoT/"],
                        ["Parque Nacional Chirripo", "/DestinoChirripo/"],
                        ["Parque Nacional Santa Rosa", "/DestinoSantaRosa/"],
                        ["Parque Nacional La Amistad", "/DestinoLaAmistad/"],
                        ["Refugio Nacional Gandoca Manzanillo", "/DestinoGandoca/"],
                        ["Refugio Cano Negro", "/DestinoCanoNegro/"],
                        ["Parque Nacional Braulio Carrillo", "/DestinoBraulioCarrillo/"],
                        ["Parque Nacional Barra Honda", "/DestinoBarraHonda/"]],

                "Medio de Transporte":[["Avion", "/Avion/"],
                                       ["Taxi", "/Taxi/"],
                                       ["Bus", "/Bus/"],
                                       ["Tren", "/Tren/"],
                                       ["Mejor ruta entre todos los medios", "/mejor_ruta/"],
                                       ]}

    return matriz
